# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from uxmate_client.uxmate_client.update_session_from_text_request import UpdateSessionFromTextRequest

class TestUpdateSessionFromTextRequest(unittest.TestCase):
    """UpdateSessionFromTextRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateSessionFromTextRequest:
        """Test UpdateSessionFromTextRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateSessionFromTextRequest`
        """
        model = UpdateSessionFromTextRequest()
        if include_optional:
            return UpdateSessionFromTextRequest(
                text_prompt = ''
            )
        else:
            return UpdateSessionFromTextRequest(
                text_prompt = '',
        )
        """

    def testUpdateSessionFromTextRequest(self):
        """Test UpdateSessionFromTextRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
