# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uxmate_client.onboarding_api import OnboardingApi


class TestOnboardingApi(unittest.TestCase):
    """OnboardingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OnboardingApi()

    def tearDown(self) -> None:
        pass

    def test_create_onboarding(self) -> None:
        """Test case for create_onboarding

        Create Onboarding
        """
        pass

    def test_summarize_onboarding(self) -> None:
        """Test case for summarize_onboarding

        Summarize
        """
        pass

    def test_update_onboarding(self) -> None:
        """Test case for update_onboarding

        Update Onboarding
        """
        pass


if __name__ == '__main__':
    unittest.main()
