# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from uxmate_client.models.get_survey_insight_response import GetSurveyInsightResponse

class TestGetSurveyInsightResponse(unittest.TestCase):
    """GetSurveyInsightResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSurveyInsightResponse:
        """Test GetSurveyInsightResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSurveyInsightResponse`
        """
        model = GetSurveyInsightResponse()
        if include_optional:
            return GetSurveyInsightResponse(
                survey_insight = ''
            )
        else:
            return GetSurveyInsightResponse(
                survey_insight = '',
        )
        """

    def testGetSurveyInsightResponse(self):
        """Test GetSurveyInsightResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
