# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from uxmate_client.uxmate_client.trend_status import TrendStatus

class TestTrendStatus(unittest.TestCase):
    """TrendStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrendStatus(self):
        """Test TrendStatus"""
        # inst = TrendStatus()

if __name__ == '__main__':
    unittest.main()
