# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uxmate_client.routines_api import RoutinesApi


class TestRoutinesApi(unittest.TestCase):
    """RoutinesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RoutinesApi()

    def tearDown(self) -> None:
        pass

    def test_create_routine(self) -> None:
        """Test case for create_routine

        Create Routine
        """
        pass

    def test_delete_routine(self) -> None:
        """Test case for delete_routine

        Delete Routine
        """
        pass

    def test_get_routines(self) -> None:
        """Test case for get_routines

        Get Routines
        """
        pass

    def test_run_async_routine(self) -> None:
        """Test case for run_async_routine

        Run Async Routine
        """
        pass

    def test_run_routine(self) -> None:
        """Test case for run_routine

        Run Routine
        """
        pass


if __name__ == '__main__':
    unittest.main()
