# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.headers_any_of_value import HeadersAnyOfValue

class TestHeadersAnyOfValue(unittest.TestCase):
    """HeadersAnyOfValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HeadersAnyOfValue:
        """Test HeadersAnyOfValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HeadersAnyOfValue`
        """
        model = HeadersAnyOfValue()
        if include_optional:
            return HeadersAnyOfValue(
                description = None,
                required = None,
                deprecated = None,
                style = None,
                explode = None,
                allow_reserved = None,
                var_schema = None,
                example = None,
                examples = None,
                content = None,
                ref = None
            )
        else:
            return HeadersAnyOfValue(
                ref = None,
        )
        """

    def testHeadersAnyOfValue(self):
        """Test HeadersAnyOfValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
