# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from uxmate_client.uxmate_client.session_status import SessionStatus

class TestSessionStatus(unittest.TestCase):
    """SessionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionStatus(self):
        """Test SessionStatus"""
        # inst = SessionStatus()

if __name__ == '__main__':
    unittest.main()
