# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uxmate_client.sessions_api import SessionsApi


class TestSessionsApi(unittest.TestCase):
    """SessionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_session_from_text(self) -> None:
        """Test case for create_session_from_text

        Create Session From Text
        """
        pass

    def test_get_grouped_sessions(self) -> None:
        """Test case for get_grouped_sessions

        Get Grouped Sessions
        """
        pass

    def test_get_session(self) -> None:
        """Test case for get_session

        Get Session
        """
        pass

    def test_get_sessions(self) -> None:
        """Test case for get_sessions

        Get Sessions
        """
        pass

    def test_update_session(self) -> None:
        """Test case for update_session

        Update Session
        """
        pass


if __name__ == '__main__':
    unittest.main()
