# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from uxmate_client.uxmate_client.session_summary import SessionSummary

class TestSessionSummary(unittest.TestCase):
    """SessionSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionSummary:
        """Test SessionSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionSummary`
        """
        model = SessionSummary()
        if include_optional:
            return SessionSummary(
                id = '',
                agent = uxmate_client.models.agent.Agent(
                    id = '', 
                    name = '', 
                    assistant_id = '', 
                    assistant_nickname = '', 
                    welcome_message = '', 
                    user_initial_message = '', 
                    icon = '', 
                    visibility_requirements = [
                        ''
                        ], ),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = ''
            )
        else:
            return SessionSummary(
                id = '',
                agent = uxmate_client.models.agent.Agent(
                    id = '', 
                    name = '', 
                    assistant_id = '', 
                    assistant_nickname = '', 
                    welcome_message = '', 
                    user_initial_message = '', 
                    icon = '', 
                    visibility_requirements = [
                        ''
                        ], ),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
        )
        """

    def testSessionSummary(self):
        """Test SessionSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
