# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.schema_external_docs import SchemaExternalDocs

class TestSchemaExternalDocs(unittest.TestCase):
    """SchemaExternalDocs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchemaExternalDocs:
        """Test SchemaExternalDocs
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchemaExternalDocs`
        """
        model = SchemaExternalDocs()
        if include_optional:
            return SchemaExternalDocs(
                description = None,
                url = None
            )
        else:
            return SchemaExternalDocs(
                url = None,
        )
        """

    def testSchemaExternalDocs(self):
        """Test SchemaExternalDocs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
