# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from uxmate_client.uxmate_client.create_template_request import CreateTemplateRequest

class TestCreateTemplateRequest(unittest.TestCase):
    """CreateTemplateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTemplateRequest:
        """Test CreateTemplateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTemplateRequest`
        """
        model = CreateTemplateRequest()
        if include_optional:
            return CreateTemplateRequest(
                survey_id = '',
                system_message = '',
                system_message_params = None,
                agent_initial_message = '',
                agent_initial_message_params = [
                    ''
                    ],
                summary_single_prompt = '',
                summary_single_prompt_params = None,
                get_insight_prompt = '',
                get_insight_prompt_params = None
            )
        else:
            return CreateTemplateRequest(
                survey_id = '',
        )
        """

    def testCreateTemplateRequest(self):
        """Test CreateTemplateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
