# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from uxmate_client.models.external_documentation import ExternalDocumentation

class TestExternalDocumentation(unittest.TestCase):
    """ExternalDocumentation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalDocumentation:
        """Test ExternalDocumentation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalDocumentation`
        """
        model = ExternalDocumentation()
        if include_optional:
            return ExternalDocumentation(
                description = None,
                url = None
            )
        else:
            return ExternalDocumentation(
                url = None,
        )
        """

    def testExternalDocumentation(self):
        """Test ExternalDocumentation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
