# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uxmate_client.business_api import BusinessApi


class TestBusinessApi(unittest.TestCase):
    """BusinessApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BusinessApi()

    def tearDown(self) -> None:
        pass

    def test_delete_business(self) -> None:
        """Test case for delete_business

        Delete Business
        """
        pass

    def test_get_business(self) -> None:
        """Test case for get_business

        Get Business
        """
        pass

    def test_update_business(self) -> None:
        """Test case for update_business

        Update Business
        """
        pass


if __name__ == '__main__':
    unittest.main()
