# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from uxmate_client.models.examples_any_of_value import ExamplesAnyOfValue

class TestExamplesAnyOfValue(unittest.TestCase):
    """ExamplesAnyOfValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExamplesAnyOfValue:
        """Test ExamplesAnyOfValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExamplesAnyOfValue`
        """
        model = ExamplesAnyOfValue()
        if include_optional:
            return ExamplesAnyOfValue(
                summary = None,
                description = None,
                value = None,
                external_value = None,
                ref = None
            )
        else:
            return ExamplesAnyOfValue(
                ref = None,
        )
        """

    def testExamplesAnyOfValue(self):
        """Test ExamplesAnyOfValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
