# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from uxmate_client.uxmate_client.create_business_and_survey_request import CreateBusinessAndSurveyRequest

class TestCreateBusinessAndSurveyRequest(unittest.TestCase):
    """CreateBusinessAndSurveyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBusinessAndSurveyRequest:
        """Test CreateBusinessAndSurveyRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBusinessAndSurveyRequest`
        """
        model = CreateBusinessAndSurveyRequest()
        if include_optional:
            return CreateBusinessAndSurveyRequest(
                survey_name = '',
                survey_description = '',
                business_name = '',
                business_description = '',
                system_prompt = '',
                initial_message = '',
                quota = 56
            )
        else:
            return CreateBusinessAndSurveyRequest(
                survey_name = '',
                survey_description = '',
                business_name = '',
                business_description = '',
                system_prompt = '',
                initial_message = '',
        )
        """

    def testCreateBusinessAndSurveyRequest(self):
        """Test CreateBusinessAndSurveyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
