# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CreateTemplateRequest(BaseModel):
    """
    CreateTemplateRequest
    """ # noqa: E501
    survey_id: StrictStr
    system_message: Optional[StrictStr] = None
    system_message_params: Optional[Any] = None
    agent_initial_message: Optional[StrictStr] = None
    agent_initial_message_params: Optional[List[StrictStr]] = None
    summary_single_prompt: Optional[StrictStr] = None
    summary_single_prompt_params: Optional[Any] = None
    get_insight_prompt: Optional[StrictStr] = None
    get_insight_prompt_params: Optional[Any] = None
    __properties: ClassVar[List[str]] = ["survey_id", "system_message", "system_message_params", "agent_initial_message", "agent_initial_message_params", "summary_single_prompt", "summary_single_prompt_params", "get_insight_prompt", "get_insight_prompt_params"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CreateTemplateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of system_message_params
        if self.system_message_params:
            _dict['system_message_params'] = self.system_message_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of summary_single_prompt_params
        if self.summary_single_prompt_params:
            _dict['summary_single_prompt_params'] = self.summary_single_prompt_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of get_insight_prompt_params
        if self.get_insight_prompt_params:
            _dict['get_insight_prompt_params'] = self.get_insight_prompt_params.to_dict()
        # set to None if system_message (nullable) is None
        # and model_fields_set contains the field
        if self.system_message is None and "system_message" in self.model_fields_set:
            _dict['system_message'] = None

        # set to None if system_message_params (nullable) is None
        # and model_fields_set contains the field
        if self.system_message_params is None and "system_message_params" in self.model_fields_set:
            _dict['system_message_params'] = None

        # set to None if agent_initial_message (nullable) is None
        # and model_fields_set contains the field
        if self.agent_initial_message is None and "agent_initial_message" in self.model_fields_set:
            _dict['agent_initial_message'] = None

        # set to None if summary_single_prompt (nullable) is None
        # and model_fields_set contains the field
        if self.summary_single_prompt is None and "summary_single_prompt" in self.model_fields_set:
            _dict['summary_single_prompt'] = None

        # set to None if summary_single_prompt_params (nullable) is None
        # and model_fields_set contains the field
        if self.summary_single_prompt_params is None and "summary_single_prompt_params" in self.model_fields_set:
            _dict['summary_single_prompt_params'] = None

        # set to None if get_insight_prompt (nullable) is None
        # and model_fields_set contains the field
        if self.get_insight_prompt is None and "get_insight_prompt" in self.model_fields_set:
            _dict['get_insight_prompt'] = None

        # set to None if get_insight_prompt_params (nullable) is None
        # and model_fields_set contains the field
        if self.get_insight_prompt_params is None and "get_insight_prompt_params" in self.model_fields_set:
            _dict['get_insight_prompt_params'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CreateTemplateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "survey_id": obj.get("survey_id"),
            "system_message": obj.get("system_message"),
            "system_message_params": AnyOf.from_dict(obj.get("system_message_params")) if obj.get("system_message_params") is not None else None,
            "agent_initial_message": obj.get("agent_initial_message"),
            "agent_initial_message_params": obj.get("agent_initial_message_params"),
            "summary_single_prompt": obj.get("summary_single_prompt"),
            "summary_single_prompt_params": AnyOf.from_dict(obj.get("summary_single_prompt_params")) if obj.get("summary_single_prompt_params") is not None else None,
            "get_insight_prompt": obj.get("get_insight_prompt"),
            "get_insight_prompt_params": AnyOf.from_dict(obj.get("get_insight_prompt_params")) if obj.get("get_insight_prompt_params") is not None else None
        })
        return _obj


