# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CreateSurveyRequest(BaseModel):
    """
    CreateSurveyRequest
    """ # noqa: E501
    business_id: Optional[StrictStr] = None
    business_name: Optional[StrictStr] = ''
    business_description: Optional[StrictStr] = ''
    survey_name: StrictStr
    survey_description: StrictStr
    quota: Optional[StrictInt] = 1000
    initial_message: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["business_id", "business_name", "business_description", "survey_name", "survey_description", "quota", "initial_message"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CreateSurveyRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if business_id (nullable) is None
        # and model_fields_set contains the field
        if self.business_id is None and "business_id" in self.model_fields_set:
            _dict['business_id'] = None

        # set to None if initial_message (nullable) is None
        # and model_fields_set contains the field
        if self.initial_message is None and "initial_message" in self.model_fields_set:
            _dict['initial_message'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CreateSurveyRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "business_id": obj.get("business_id"),
            "business_name": obj.get("business_name") if obj.get("business_name") is not None else '',
            "business_description": obj.get("business_description") if obj.get("business_description") is not None else '',
            "survey_name": obj.get("survey_name"),
            "survey_description": obj.get("survey_description"),
            "quota": obj.get("quota") if obj.get("quota") is not None else 1000,
            "initial_message": obj.get("initial_message")
        })
        return _obj


