# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, StrictStr
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GetTemplateResponse(BaseModel):
    """
    GetTemplateResponse
    """ # noqa: E501
    template_id: StrictStr
    survey_id: StrictStr
    system_message: StrictStr
    system_message_params: List[StrictStr]
    agent_initial_message: StrictStr
    agent_initial_message_params: List[StrictStr]
    summary_single_prompt: StrictStr
    summary_single_prompt_params: List[StrictStr]
    get_insight_prompt: StrictStr
    get_insight_prompt_params: List[StrictStr]
    __properties: ClassVar[List[str]] = ["template_id", "survey_id", "system_message", "system_message_params", "agent_initial_message", "agent_initial_message_params", "summary_single_prompt", "summary_single_prompt_params", "get_insight_prompt", "get_insight_prompt_params"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GetTemplateResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GetTemplateResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "template_id": obj.get("template_id"),
            "survey_id": obj.get("survey_id"),
            "system_message": obj.get("system_message"),
            "system_message_params": obj.get("system_message_params"),
            "agent_initial_message": obj.get("agent_initial_message"),
            "agent_initial_message_params": obj.get("agent_initial_message_params"),
            "summary_single_prompt": obj.get("summary_single_prompt"),
            "summary_single_prompt_params": obj.get("summary_single_prompt_params"),
            "get_insight_prompt": obj.get("get_insight_prompt"),
            "get_insight_prompt_params": obj.get("get_insight_prompt_params")
        })
        return _obj


