# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from uxmate_client.models.chat_history import ChatHistory
from uxmate_client.models.survey_record_state import SurveyRecordState
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GetOrCreateSurveyRecordResponse(BaseModel):
    """
    GetOrCreateSurveyRecordResponse
    """ # noqa: E501
    survey_id: StrictStr
    record_id: StrictStr
    chat_history: ChatHistory
    record_state: SurveyRecordState
    description: StrictStr
    survey_name: StrictStr
    assistant_name: Optional[StrictStr] = 'Assistant'
    __properties: ClassVar[List[str]] = ["survey_id", "record_id", "chat_history", "record_state", "description", "survey_name", "assistant_name"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GetOrCreateSurveyRecordResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of chat_history
        if self.chat_history:
            _dict['chat_history'] = self.chat_history.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GetOrCreateSurveyRecordResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "survey_id": obj.get("survey_id"),
            "record_id": obj.get("record_id"),
            "chat_history": ChatHistory.from_dict(obj.get("chat_history")) if obj.get("chat_history") is not None else None,
            "record_state": obj.get("record_state"),
            "description": obj.get("description"),
            "survey_name": obj.get("survey_name"),
            "assistant_name": obj.get("assistant_name") if obj.get("assistant_name") is not None else 'Assistant'
        })
        return _obj


