# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, StrictStr
from uxmate_client.models.data_source import DataSource
from uxmate_client.models.session import Session
from uxmate_client.models.trend import Trend
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RoutineWithSessions(BaseModel):
    """
    RoutineWithSessions
    """ # noqa: E501
    id: StrictStr
    agent_id: StrictStr
    name: StrictStr
    requirements: StrictStr
    interval: StrictStr
    trend: Trend
    data_source: DataSource
    sessions: List[Session]
    latest_answer: StrictStr
    __properties: ClassVar[List[str]] = ["id", "agent_id", "name", "requirements", "interval", "trend", "data_source", "sessions", "latest_answer"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RoutineWithSessions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of trend
        if self.trend:
            _dict['trend'] = self.trend.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data_source
        if self.data_source:
            _dict['data_source'] = self.data_source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sessions (list)
        _items = []
        if self.sessions:
            for _item in self.sessions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['sessions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RoutineWithSessions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "agent_id": obj.get("agent_id"),
            "name": obj.get("name"),
            "requirements": obj.get("requirements"),
            "interval": obj.get("interval"),
            "trend": Trend.from_dict(obj.get("trend")) if obj.get("trend") is not None else None,
            "data_source": DataSource.from_dict(obj.get("data_source")) if obj.get("data_source") is not None else None,
            "sessions": [Session.from_dict(_item) for _item in obj.get("sessions")] if obj.get("sessions") is not None else None,
            "latest_answer": obj.get("latest_answer")
        })
        return _obj


